# Generated by Django 6.1 on 2026-08-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=8)),
                ('destination', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='pending', max_length=32)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('amount', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=8)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.product')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
